added get-creds step for users coming from step 5
mspnp/aks-fabrikam-dronedelivery pull request #10
Opened 2021-04-28 08:57 UTC by Mahesh-MSFT

users coming from step 5 (option 2 - gitops) should set the AKS context first before running `kubectl get constrainttemplate`

2021-05-07 20:28 UTC, ferantivero requested changes
thanks again @Mahesh-MSFT we do love all contributions as usual. Please let us shared some comments on top of this one.

2021-05-07 20:28 UTC, ferantivero commented on 07-workload-prerequisites.md
> +    ```bash
it seems the indentation is not correct. Could you please take a look at this?

2021-05-07 20:28 UTC, ferantivero commented on 01-prerequisites.md
> +1. Run `export MSYS_NO_PATHCONV=1` to avoid PATH mangling.
could you please tell us a bit more about this? 

It is expected that Windows users go over WLS to follow this instructions, isn't that working on your environment?

2021-05-10 09:24 UTC, Mahesh-MSFT commented on 01-prerequisites.md
> +1. Run `export MSYS_NO_PATHCONV=1` to avoid PATH mangling.
End-to-end set up instructions are about 350+ lines! 

I couldn't run all instructions in one sitting. I think most developers won't be able to run all instructions in one sitting either.
 
I used VS code on Windows, created a script file, copied the instructions in that script file so that it's easy for me to just select from previous day and continue to add new instructions as I go along. I used VS code integrated bash terminal. I could have chosen WSL as well. But it's not the terminal but the editor which causes the mangled paths.

2021-05-10 09:30 UTC, Mahesh-MSFT commented on 07-workload-prerequisites.md
> +    ```bash
this appears to be unintended (pun intended :-)). will fix anyways.

2021-05-10 14:58 UTC, ferantivero commented on 01-prerequisites.md
> +1. Run `export MSYS_NO_PATHCONV=1` to avoid PATH mangling.
thanks for adding this perspective @Mahesh-MSFT, please let me say that we know that in the users' organizations,   portions of this will end in a script for the sake of simplicity and make it more repeatable.

I see what you are doing in there 😸; But in my opinion, that single command execution is not telling the complete story. 

Therefore, here are our proposed route of actions for this:

1. Please let's revert [3ade7](https://github.com/mspnp/aks-fabrikam-dronedelivery/pull/10/commits/3ade71844e059b79c4362d18dcb889fb29de4e63) for the moment. We could take this contribution into account the future.
1. Could you please convert this command line execution into an optional note in which you tell the developers briefly that if they are willing to create a script using VS Code in Windows, they might need to use it for the mangled paths or something similar.

2021-05-10 17:25 UTC, Mahesh-MSFT commented on 01-prerequisites.md
> +1. Run `export MSYS_NO_PATHCONV=1` to avoid PATH mangling.
i have converted explicit instruction to a note/bulb. hope that is okay :-)

2021-05-12 16:15 UTC, ferantivero commented on 01-prerequisites.md
> +1. Run `export MSYS_NO_PATHCONV=1` to avoid PATH mangling.
it is a great addition 💪

2021-05-12 16:15 UTC, ferantivero approved these changes

2021-05-12 16:16 UTC, ferantivero commented
Please let us merge this contrib. @Mahesh-MSFT and thanks again!

Keep them coming!

2021-05-12 16:17 UTC, merged