Modified deployment instructions to use shared fabrikam-worklaod repo (advanced scenario)
mspnp/aks-fabrikam-dronedelivery pull request #13
Opened 2021-05-07 17:33 UTC by magrande

2021-05-07 19:15 UTC, ckittel commented
I'm going to defer on this one to @ferantivero -- in case we want to pin to a specifc tag on the new repo for reliability in execution or submodule or if this is fine to do it this way.

2021-05-07 19:21 UTC, ferantivero commented on 01-prerequisites.md
> +1. Clone/download these repos locally, or even better, fork these repositories.
yeah, as @ckittel shared over the convo section. Please let's add a submodule for this. I think that would be the right move for this.

2021-05-07 19:33 UTC, ferantivero commented on 09-workload.md
> +   az acr build -r $ACR_NAME -t $ACR_SERVER/ingestion:0.1.0 ../aks-fabrikam-dronedelivery-workload/src/shipping/ingestion/.
I would love we experiment moving these instructions over the new repo's readme, and make our users go over there more like a pre-req (please note it will be just another folder).

It might require some ARM template changes for ACR purposes.

2021-05-07 19:50 UTC, ckittel commented on 09-workload.md
> +   az acr build -r $ACR_NAME -t $ACR_SERVER/delivery:0.1.0 ../aks-fabrikam-dronedelivery-workload/src/shipping/delivery/.
Sorry, that was my name choice `aks-fabrikam-dronedelivery-workload` -- only because I assumed there were helm charts and other kubernetes artifacts in the repo that mostly kept it AKS-centric -- and it laid next to `aks-fabrikam-dronedelivery` repo so nice in the list :)

2021-05-07 19:52 UTC, ckittel commented on 09-workload.md
> +   az acr build -r $ACR_NAME -t $ACR_SERVER/ingestion:0.1.0 ../aks-fabrikam-dronedelivery-workload/src/shipping/ingestion/.
I'd like to see that too <3, so we don't have to duplicate these instructions in both places.  Maybe he can do that when he updates the other repo as well? or as a PR after that other repo gets updated.

2021-05-07 20:43 UTC, ferantivero commented on 09-workload.md
> +   az acr build -r $ACR_NAME -t $ACR_SERVER/ingestion:0.1.0 ../aks-fabrikam-dronedelivery-workload/src/shipping/ingestion/.
Oh I see, yeah we could definitely do that. So I'd defer to you one this one. 

That said please let's resolve this via another AzDO task if needed. Or just keep this one blocking until we get it done from the another repo and modified in here as well. 

I originally proposed the later knowing we incur in some delays ⏳ but could guarantee us to get the laser focus on this 🎯

2021-05-07 20:48 UTC, ferantivero commented
> I'm going to defer on this one to @ferantivero -- in case we want to pin to a specifc tag on the new repo for reliability in execution or submodule or if this is fine to do it this way.

@chad  @neilpeterson I always dreamed we publish these images from `mcr`. I've seen similar images out there in the past. How easier will be our lives 🍰

2021-05-10 15:05 UTC, magrande commented on 09-workload.md
> +   az acr build -r $ACR_NAME -t $ACR_SERVER/delivery:0.1.0 ../aks-fabrikam-dronedelivery-workload/src/shipping/delivery/.
@ckittel Can you please rename the shared repo to fabrikam-dronedelivery-workload ? So, then after it's renamed I can create a submodule ?

2021-05-11 13:09 UTC, magrande commented on 09-workload.md
> +   az acr build -r $ACR_NAME -t $ACR_SERVER/ingestion:0.1.0 ../aks-fabrikam-dronedelivery-workload/src/shipping/ingestion/.
Here is a PR that addresses this movement. Please take a look

https://github.com/mspnp/aks-fabrikam-dronedelivery-workload/pull/3

2021-05-21 14:22 UTC, ckittel requested changes
Just applying feedback on the NetworkPolicy change, not the rest of the changes.  I want to make sure we're all in agreeance that now that the bug was found/resolved, this is HOW we want the new policies to be.  Especially since networkpolicy/zero-trust is such an important concept on these pages.  Does this change invalidate anything written in the RA as well?

2021-05-21 14:22 UTC, ckittel commented on charts/delivery/templates/delivery-networkpolicy-allow-egress-traffic.yaml
> -        - {{ required "networkPolicy.egress.external.clusterSubnetPrefix is required to enable external traffic" .Values.networkPolicy.egress.external.clusterSubnetPrefix }}
Is there a better solution here than just opening it up to all ranges for egress?  Like to just specific pods.  @ferantivero -- this gets back to the "two styles" of firewall rules.  Also @magrande -- each of these files have a comment that no longer matches the rule.  You'll want to update the comment to match this new situation.

Does this even need to be a helm chart param anymore? there was what looked to be FIVE usages of this, and you've eliminated FOUR of them.  What's the fifth usage and should that go away (along with the helm value as well)?

2021-05-21 20:48 UTC, ferantivero commented on charts/delivery/templates/delivery-networkpolicy-allow-egress-traffic.yaml
> -        - {{ required "networkPolicy.egress.external.clusterSubnetPrefix is required to enable external traffic" .Values.networkPolicy.egress.external.clusterSubnetPrefix }}
as discussed @magrande please let's revisit our decision in here as it seems we might be overriding our original zero-trust and that's why it'd started to work.

2021-05-21 21:03 UTC, ferantivero commented on charts/delivery/templates/delivery-networkpolicy-allow-egress-traffic.yaml
> -        - {{ required "networkPolicy.egress.external.clusterSubnetPrefix is required to enable external traffic" .Values.networkPolicy.egress.external.clusterSubnetPrefix }}
if the approach I commented works, we could consider revert or at least mention that this action is going to be a remediation for 78b73ccd596e8dadb4e4980c783511fa600d528c

2021-05-24 19:05 UTC, magrande commented on 01-prerequisites.md
> +1. Clone/download these repos locally, or even better, fork these repositories.
Done and tested

2021-05-24 19:08 UTC, magrande commented on 09-workload.md
> +   az acr build -r $ACR_NAME -t $ACR_SERVER/ingestion:0.1.0 ../aks-fabrikam-dronedelivery-workload/src/shipping/ingestion/.
AS we agreed, we are still keeping the build and install instructions in step 09.  but using the right deployment variables (workload-stamp)  and using the path to the new submodule; the new repo (the submodule) has its own independent set of build/install instruction, though.

2021-05-24 19:12 UTC, magrande commented on charts/delivery/templates/delivery-networkpolicy-allow-egress-traffic.yaml
> -        - {{ required "networkPolicy.egress.external.clusterSubnetPrefix is required to enable external traffic" .Values.networkPolicy.egress.external.clusterSubnetPrefix }}
Ok. this change was reverted since we were allowing egress traffic to everything in the pods.  We needed a fix though, so after a conversation with Chad we agreed we should add a new "To"  to the workflow's network policies, in order to allow it to communicate with the pods in the cluster, since after AKS team applied the fix it stopped working. There isn't a prevalence between ingress and egress policies, they both work together, so we needed this new "To" block in the workflow's egress policy.  I tested this change and it worked.

2021-05-26 20:26 UTC, ckittel commented on charts/workflow/templates/workflow-networkpolicy-allow-egress-traffic.yaml
> +        - podSelector: {}
Nit (hopefully doesn't impact results): may be off a bit on the whitespace on this line. Can you double check that?

2021-05-26 20:40 UTC, ckittel commented on 01-prerequisites.md
> +    git submodule add $WL_GITHUB_REPO workload
Isn't this just a `--recurse-submodules` on the initial clone?

2021-05-26 20:41 UTC, ckittel requested changes
Just two comments (above -- sorry, they didn't get included in the actual review here -- I fat fingered the comment UI here in GitHub ... TWICE :))

2021-05-26 23:05 UTC, magrande commented on 01-prerequisites.md
> +    git submodule add $WL_GITHUB_REPO workload
The simpler the better...

2021-05-26 23:21 UTC, magrande commented on charts/workflow/templates/workflow-networkpolicy-allow-egress-traffic.yaml
> +        - podSelector: {}
Yes, wrong indent. Fixed and tested, no impact !

2021-05-26 23:23 UTC, ckittel approved these changes
From my perspective, looks good. But works like to defer to @ferantivero for final review. Nice work @magrande!

2021-05-27 16:50 UTC, ferantivero approved these changes
well done @magrande LGTM 🚀

2021-05-27 16:52 UTC, ferantivero commented on 09-workload.md
> +   az acr build -r $ACR_NAME -f ./workload/src/shipping/dronescheduler/Dockerfile -t $ACR_SERVER/dronescheduler:0.1.0 ./workload/src/shipping/.
why is this still in here?

2021-05-27 17:20 UTC, magrande commented on 05-aks-cluster.md
> +   az deployment group create --resource-group rg-shipping-dronedelivery --template-file cluster-stamp.json --parameters targetVnetResourceId=$TARGET_VNET_RESOURCE_ID k8sRbacAadProfileAdminGroupObjec
Done, I've created a task in GH backlog to track this.

2021-05-27 17:24 UTC, merged